services:
  - type: web
    name: agroconnect-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://agroconnect-backend-hl8l.onrender.com/api
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Cache-Control
        value: no-cache
    # Handle SPA routing - all routes should serve index.html
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/:splat
      - type: rewrite
        source: /*
        destination: /index.html
